### ISSUE TITLE
.net core library

### ISSUE THREAD

**Issue by jiayangkai** [PySEE/SEUIF97#2]
@thermalogic @chengts95 my company has a Cross-platform project with .net core and want to use SEUIF97,  can you provide the library with .net core 3.0?
Thank you and look forward to your reply!

**Comment by thermalogic** [comment]
SEUIF97 is the shared library for all programing language, you may call the  shared library through the specified API for your programing language

**Comment by jiayangkai** [comment]
@thermalogic Although conventional DLL can be used in a native Windows environment, it can’t be used in .NET Core cross platform environment. However, it is straightforward to recompile it for .NET Core. As cross platform applications are increasingly used, supporting .NET Core will make this library more widely used by the community. You can find information about .NET Core here: https://docs.microsoft.com/en-us/dotnet/core/.   And we are happy to provide additional information on how to recompile this library as an additional package and help to test it.

**Comment by thermalogic** [comment]
For the cross-platform application,we compile the C codes into the specified platform shared library.  
We have provided the so library for Linux-X64. You can call the so library from .NET Core through C# API

**Comment by jiayangkai** [comment]
@thermalogic What you’ve suggested in calling DLlL from .NET Core in a Windows environment and switching to .so in Linux would/might work but it introduces complexity to the cross platform packaging etc. It would be much simpler to include this library as a .NET Core library no matter if the apps are run in Windows or Linux. Just curious about Any particular concerns you have in providing a .NET Core library.

**Comment by chengts95** [comment]
There is no reason to recomplie a C library to .Net.  Java and Python have unified interface to use native library (also the library name itself doesn't contain the suffix in C/C++ complier) so the C# should also provide the unified interface (however C# was limited to windows .Net for a very long time). If it cannot, it is not good enough to go cross platform.

**Comment by jiayangkai** [comment]
First of all, thank you for your reply and suggestions.
Because .NET Core has become an important choice for Windows and Linux cross-platform solutions, its lack of support will limit the wider use of this software.Many times the success of a thing depends not only on whether it can be achieved, but also on how easy it is to achieve.
At the same time you can look at the Microsoft 2019 Developer Conference and the latest release plan, the next version of .Net Core 3.0 will be .Net 5. .NET Framework will not be updated.For Windows application development, cross-platform will be the trend and the only choice.You can search for relevant news, all the content is explaining this.

**Comment by chengts95** [comment]
Thanks for the introduction. However, I have no interest in .NET and I am not windows application developer. I can do everything in C++ and python and make them cross platform.
